// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using TG.Payroll.Web.Data;

#nullable disable

namespace TG.Payroll.Web.Data.Migrations
{
    [DbContext(typeof(PayrollDbContext))]
    [Migration("20260815060117_UsersBaseline")]
    partial class UsersBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TG.Payroll.Web.Models.PayrollUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USER_ID");

                    b.Property<decimal?>("Admin")
                        .HasColumnType("NUMBER")
                        .HasColumnName("ADMIN");

                    b.Property<decimal?>("CallingId")
                        .HasColumnType("NUMBER")
                        .HasColumnName("CALLING_ID");

                    b.Property<string>("CompanyId")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("COMPANY_ID");

                    b.Property<string>("DefaultMenuCalander")
                        .HasMaxLength(1)
                        .HasColumnType("VARCHAR2(1)")
                        .HasColumnName("DEFAULT_MENU_CALANDER");

                    b.Property<string>("EmpCode")
                        .HasMaxLength(15)
                        .HasColumnType("VARCHAR2(15)")
                        .HasColumnName("EMP_CODE");

                    b.Property<int?>("EmpId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("EMP_ID");

                    b.Property<decimal?>("IsLock")
                        .HasColumnType("NUMBER")
                        .HasColumnName("IS_LOCK");

                    b.Property<decimal?>("LoginStatus")
                        .HasColumnType("NUMBER")
                        .HasColumnName("LOGIN_STATUS");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Photo")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("PHOTO");

                    b.Property<string>("PrivilegeArray")
                        .HasMaxLength(4000)
                        .HasColumnType("VARCHAR2(4000)")
                        .HasColumnName("PRIVILEGE_ARRAY");

                    b.Property<string>("Remarks")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50)")
                        .HasColumnName("REMARKS");

                    b.Property<string>("UserName")
                        .HasMaxLength(80)
                        .HasColumnType("VARCHAR2(80)")
                        .HasColumnName("USER_NAME");

                    b.HasKey("UserId");

                    b.ToTable("USERS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
